version: '3.7'
services:
  todos:
    build:
      context: .
      dockerfile: Dockerfile.app
      cache_from:
      - golang:1.12.7
      - alpine:3.9.4
    ports:
      - 3000:3000
    depends_on:
    - purple
  purple:
    build:
      context: .
      dockerfile: Dockerfile.grpc
      cache_from:
      - znly/protoc:0.4.0
      - golang:1.12.7
      - alpine:3.9.4
    ports:
    - 8080:8080
    command: ["--backend", "redis", "--redis-url" , "redis:6379"]
    depends_on:
    - redis
  redis:
    image: redis
    ports:
    - 6379:6379
