---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: purple-http
  labels:
    app: purple
spec:
  replicas: 1
  selector:
    matchLabels:
      app: purple
  template:
    metadata:
      labels:
        app: purple
    spec:
      containers:
        - name: purple-grpc
          image: lucperkins/purple-http:latest
          ports:
            - containerPort: 8081
          args: ["--port", "8081", "--backend", "redis", "--redis-url", "redis:6379"]
---
apiVersion: v1
kind: Service
metadata:
  name: purple-http
  labels:
    run: purple
spec:
  ports:
  - port: 8081
    protocol: TCP
  selector:
    run: purple
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: master
          image: redis
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: purple-http-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  backend:
    serviceName: purple-http
    servicePort: 8080
