---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strato-grpc
  labels:
    app: strato
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strato
  template:
    metadata:
      labels:
        app: strato
    spec:
      containers:
      - name: strato-grpc
        image: lucperkins/strato-grpc:v0.1.2
        ports:
        - containerPort: 8080
        args: ["--port", "8080", "--backend", "redis", "--redis-url", "redis:6379"]
---
apiVersion: v1
kind: Service
metadata:
  name: strato-grpc
  labels:
    run: strato
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 31234
    protocol: TCP
  selector:
    run: strato
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: master
        image: redis
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: strato-grpc-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  backend:
    serviceName: strato-grpc
    servicePort: 80
